### ISSUE TITLE
newpos,newvowelindexes,countweight len not equal

### ISSUE THREAD

**Issue by aneybaby727** [somnat/Hindi-word-prosody#1]
when i use I-Level_Syllabification to get  Syll_label, i get that bug
newpos  len is 16;
newvowelindexes len  is 7 
countweight  len is  20
Traceback (most recent call last):
  File "input.py", line 67, in <module>
    Labeling(line.strip())
  File "/data3/zhangyan/tacotron2-master-nvidia/WaveRNN-master/Hindi-word-prosody_tmp/src/Syll_label.py", line 73, in Labeling
    if newpos[i] - indexvowelsnew[i] == 1 and countweight[i] == 1 and i == 0:
IndexError: list index out of range

**Comment by aneybaby727** [comment]
> when i use I-Level_Syllabification to get Syll_label, i get that bug
> newpos len is 16;
> newvowelindexes len is 7
> countweight len is 20
> Traceback (most recent call last):
> File "input.py", line 67, in
> Labeling(line.strip())
> File "/data3/zhangyan/tacotron2-master-nvidia/WaveRNN-master/Hindi-word-prosody_tmp/src/Syll_label.py", line 73, in Labeling
> if newpos[i] - indexvowelsnew[i] == 1 and countweight[i] == 1 and i == 0:
> IndexError: list index out of range

how to solve it?  thanks for your help
